### ISSUE TITLE
dotnet-addcasa.exe stop working

### ISSUE THREAD

**Issue by shameed** [cmendible/dotnet-addcasa#2]
Hi,

System configuration:
Windows 7 (64-bit)
Dotnet version 2.1.301

-Installed as administrator, got following warning
![image](https://user-images.githubusercontent.com/1008068/42435402-0863b688-8374-11e8-9fb8-729f4dc6713d.png)
- when running `dotnet addcasa ` command in the solution root folder, got following issue
![image](https://user-images.githubusercontent.com/1008068/42435576-9ee5909a-8374-11e8-831a-728d58a2b65d.png)
```
Command-line Error: Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'C:\Users\username\.dotnet\tools\dotnet-addcasa.dll'. The system
 cannot find the file specified.
```

**Thanks,
Hameed**

**Comment by cmendible** [comment]
I'm sorry about that please try installing the new version:

`dotnet tool install --global dotnet-addcasa --version 1.0.2`

And let me know if it works.

**Comment by cmendible** [comment]
Closing cause of https://github.com/cmendible/dotnet-addcasa/issues/3
