### ISSUE TITLE
dotnet-addcasa is looking for a concrete runtime (2.1.0-rc1)

### ISSUE THREAD

**Issue by snavarropino** [cmendible/dotnet-addcasa#3]
Hi, I got an error trying to execute dotnet-addcasa. It seems to require a concrete runtime that is not installed on my machine:

![imagen](https://user-images.githubusercontent.com/11868679/42567116-0a39c4b6-8509-11e8-8683-c7ebcc40b2b0.png)

Thanks

**Comment by snavarropino** [comment]
I have installed required runtime (2.1.0-rc1) from here: https://github.com/dotnet/core/blob/master/release-notes/download-archives/2.1.0-rc1-download.md

After this the tool is working fine.

I keep investigating

**Comment by cmendible** [comment]
Hmm let me check the nuget package and the code and I'll get back to you with my findings...

**Comment by cmendible** [comment]
Wow! My build server was not updated!!!. Just released version 1.0.2 with the fix. (related to: https://github.com/cmendible/dotnet-addcasa/issues/2)

**Comment by snavarropino** [comment]
Working fine now! Thanks for your prompt support

lLosing this issue
